settingMenuDesktop och ChangeLanguage/Sound/NotificationsDesktop
jensengbg-johanna-jansson/prototype-assignment pull request #28
Opened 2020-11-09 09:14 UTC by jensengbg-johanna-ohrnberg

2020-11-09 12:53 UTC, jensengbg-johanna-jansson commented on src/components/settingsComp/ChangeLanguageDesktop.vue
> +            <label class="label">English
Gör språklistan till radiobuttons istället så kan bara ett språk vara vald åtgången

2020-11-09 12:56 UTC, jensengbg-johanna-jansson commented on src/components/settingsComp/ChangeLanguageDesktop.vue
> +            <label class="label">English
Sätt en text-transform: uppercase; på alla labels så att texten blir stora bokstäver

2020-11-09 13:16 UTC, jensengbg-johanna-jansson requested changes
Såg att du har många element med id=container som jag tror ställer till det lite i din css. Ett id ska vara unikt på sidan, så helst ska bara ett element ha ett visst id, om man vill dela på css med flera element är det bättre att använda klasser. 
På min dator blir layouten lite konstig (saker får inte riktigt plats som de ska), vilket jag tror kommer från att flera element försöker lägga till #container's grid. Försök gärna skriva om din css så att du lägger alla grids i olika klasser istället för i #container, t.ex. kan du lägga dom i din .settings-menu om det bara ska gälla menyn, eller .change-language om det bara gäller det som ligger i den sectionen.

2020-11-10 08:22 UTC, elizasmir approved these changes
Det verkar som all funkar och ser bra ut. Dessutom har ändringar lagt efter först review.

Bra jobbat 👍

2020-11-10 09:21 UTC, merged